name: Go
on: [push]
jobs:

  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - uses: actions/checkout@v1
 
    - name: build
      run: |
        git submodule update --init
        export PATH=$PATH:$(go env GOPATH)/bin
        go get ./cmd/...
        kit-dev build

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: go env
      run: echo "::add-path::$(go env GOPATH)/bin"
      shell: bash

    - uses: actions/checkout@v1
  
    - name: build
      run: |
        git submodule update --init
        go get ./cmd/...
        kit-dev export
        kit-dev readme
        godev -m 90
        godev build "cmd/*" "!cmd/kit-dev"
